#!/bin/sh

set -e

if [ "$PRISON_WEBROOT_S3_URL" = "" ] ; then
  echo "--[ ERROR ]"
  echo
  echo "You must set the environment variable PRISON_WEBROOT_S3_URL to be a full S3"
  echo "path to the webroot tarball. eg., 's3://mybucketname/webroot.tar.gz'"
  echo
  exit 1
fi

echo "Extracting webroot..."
aws s3 cp "$PRISON_WEBROOT_S3_URL" /tmp/webroot.tar.gz
tar -xzf /tmp/webroot.tar.gz -C /srv/www
rm /tmp/webroot.tar.gz
chown -R apache:www-data /srv/www

echo "Starting httpd..."
/usr/sbin/httpd -D FOREGROUND -f /etc/apache2/httpd.conf
