#!/bin/sh

set -e

if ! [ -f "/appsrc/webroot.tar.gz" ] ; then
  echo "--[ ERROR ]"
  echo
  echo "No webroot found at '/appsrc/webroot.tar.gz'. Make sure this file exists and is"
  echo "a gzip'ed tarball of the webroot files you want extracted into the container."
  echo
  exit 1
fi

echo "Extracting webroot..."
tar -xzf /appsrc/webroot.tar.gz -C /srv/www
chown -R apache:www-data /srv/www

echo "Starting httpd..."
/usr/sbin/httpd -D FOREGROUND -f /etc/apache2/httpd.conf
