#!/bin/sh

set -e

if [ "$AZURE_STORAGE_WEBROOT_URL" = "" ] ; then
  echo "--[ ERROR ]"
  echo
  echo "You must set AZURE_STORAGE_WEBROOT_URL to the full URL to the webroot tarball in Azure "
  echo "Storage, suffixed with a valid Shared Access Signature (SAS)."
  echo
  echo "    e.g., 'https://<account>.blob.core.windows.net/<container>/webroot.tar.gz?<sas>'"
  echo
  exit 1
fi

export AZCOPY_BUFFER_GB=0.03

cd /srv/www
  echo "Building source tarball..."
  tar -czf /tmp/webroot.tar.gz ./

  echo "Uploading source tarball..."
  azcopy copy /tmp/webroot.tar.gz "$AZURE_STORAGE_WEBROOT_URL"
cd -

echo "Source update is complete. You will need to restart any still-running containers"
echo "for them to pick up the new webroot."
